import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartProvider } from "./context/cart-context";
import { StoreProvider } from "./context/store-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextShopAPI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col min-h-screen bg-zinc-50">
          <StoreProvider>
            <CartProvider>
              <Header />
              <div className="container mx-auto">{children}</div>
              <Footer />
            </CartProvider>
          </StoreProvider>
        </main>
      </body>
    </html>
  );
}
